- name: Update all packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Add EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Java
  ansible.builtin.yum:
    name: 
      - java-11-openjdk
    state: present

- name: Add tomcat group
  ansible.builtin.group:
    name: tomcat

- name: Add tomcat user
  ansible.builtin.user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    create_home: false
    system: true

- name: Download tomcat
  ansible.builtin.get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"
    checksum: "{{ tomcat_checksum }}"

- name: create tomcat directory
  ansible.builtin.file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Expand tomcat
  ansible.builtin.unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: true
    extra_opts: "--strip-components=1"
    creates: /usr/share/tomcat/bin

- name: Copy tomcat service file
  ansible.builtin.template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    mode: "a+x"
  when: ansible_service_mgr == "systemd"

- name: Start and Enable tomcat
  ansible.builtin.service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Open tomcat port on the firewall
  ansible.builtin.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_service_mgr == "systemd"

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: Set UI access credentials
  ansible.builtin.template:
    src: tomcat-users.xml.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restart tomcat

- name: Allow access to Manager and Host Manager apps from any IP
  ansible.builtin.template:
    src: context.xml.j2
    dest: "{{ item }}"
  with_items:
    - /usr/share/tomcat/webapps/host-manager/META-INF/context.xml
    - /usr/share/tomcat/webapps/manager/META-INF/context.xml
  notify: restart tomcat
